### ISSUE TITLE
Set tint color based on AppDelegate's window's tintColor

### ISSUE THREAD

**Issue by natanrolnik** [MosheBerman/MBPlacePickerController#2]
In MBPlacePickerController at line 190:

`NSDictionary *attributes = @{NSForegroundColorAttributeName : [[UIView appearance] tintColor]};`

If the tint color is set via the app delegate's window (the correct way to do it) - it causes a crash, because `[[UIView appearance] tintColor]` returns `nil`. The ideal here would be to access the app delegate's window's tint color, that will never be nil.

**Comment by MosheBerman** [comment]
Do you want to implement the fix and send a pull request? If not, I'm happy to do it once I have the time.

**Comment by natanrolnik** [comment]
I'll try to do it soon

**Comment by MosheBerman** [comment]
Thanks!

Shabbat shalom/shavua tov.

**Comment by natanrolnik** [comment]
@MosheBerman there is something strange. The reference I mentioned of line 190 is valid only for the CocoaPods version. The current version in master doesn't mention it.

Besides that, in the app delegate the tintColor should not be set via appearance proxy, as I don't think it goes down the view hierarchy in the same way you do calling `view.tintColor = ...` or `window.tintColor = ...`

In my pull request #3 I am fixing that as well.

Please check and merge, and then we need update the CocoaPod as well.

**Comment by MosheBerman** [comment]
This repo was used in a few of my projects, and I may have made some adjustments that accidentally found their way into the master branch. That would account for the differences.

I can't automatically merge your locations.json update for some reason, so I need to get that first.

**Comment by MosheBerman** [comment]
Merged a while ago.
